stages:
  - build
  - lint
  - test
  - deploy

# build-job:
#   stage: build
#   script:
#     - echo "Hello, $GITLAB_USER_LOGIN!"

#php-lint:
 # stage: lint
#  image: php:latest
  # allow_failure: true
  # before_script:
  #   - php --version
  # script:
  #   - php phpcs.phar --exclude=Generic.Files.LineEndings html
  #   # - php phpcbf.phar --exclude=Generic.Files.LineEndings html

# test-nginx:
#   stage: test
#   image: nginx:latest
#   before_script:
#     - nginx -v
#   script:
#     - export CURRENT_DIR=$(pwd)
#     - nginx -t -c $CURRENT_DIR/nginx.conf
unit-test:
  image: node:latest
  stage: test
  before_script:
    - cd html
    - cd test
    - npm install --save-dev jsdom 
    - npm install --save-dev jest-environment-jsdom
  script:
    - npm run waldo_game.test.js
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

deploy-prod:
  stage: deploy
  image: debian:12.4
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - chmod 400 "$SSH_PRIVATE_KEY"
  - ssh-add "$SSH_PRIVATE_KEY"
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan cis4250w24-08.socs.uoguelph.ca >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "On $CI_COMMIT_REF_NAME branch, copying html files...";
    - scp -r html/* socs@cis4250w24-08.socs.uoguelph.ca:/var/www/html/;
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  environment: production
