version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./html:/app/public
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - php
  php:
    image: php:8.2-fpm
    volumes:
      - ./html:/app/public
      - ./codesniffer:/app/codesniffer